import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import { registerLicense } from '@syncfusion/ej2-base';

registerLicense('Mgo+DSMBaFt/QHRqVVhjVFpFaV1CQmFJfFBmRmlbfVR0ckUmHVdTRHRdQ19hSH9WdUZiUX5XdXQ=;Mgo+DSMBPh8sVXJ0S0J+XE9HflRDQmFJYVF2R2BJfFRydl9CZkwxOX1dQl9hSHxRd0RmWnxfeHZUR2A=;ORg4AjUWIQA/Gnt2VVhkQlFadVdJXHxLfkx0RWFab116dldMZFpBJAtUQF1hS39RdERiXHxdcXxXRGdd;Nzg5MjQ4QDMyMzAyZTM0MmUzMEhwdkwraDRjcUZjR2xQSHhTaUFkWm9FeTgrSkEyVDNGVGlwd3ZSdnJ3eEk9;Nzg5MjQ5QDMyMzAyZTM0MmUzMEwrU3dXY1U2akFWek1MS2lDam9ua3h4UTFhUWpKVWozb3RjSnFUZHpuaUk9;NRAiBiAaIQQuGjN/V0Z+WE9EaFxKVmJWfFNpR2NbfE5zfldEalhXVBYiSV9jS3xSdEdiWHpdc3VdRGleUA==;Nzg5MjUxQDMyMzAyZTM0MmUzMEphanZFbVNQd1pIL3g4dmNqOUpSemZLR21CVEIyaHpGUU5tVmU4ZU1jN3c9;Nzg5MjUyQDMyMzAyZTM0MmUzMFBZeVhxK1d6bjdEangxQ3ovak9TWTdzQzdYYkYwOTRKcnMxODlFejBnbHc9;Mgo+DSMBMAY9C3t2VVhkQlFadVdJXHxLfkx0RWFab116dldMZFpBJAtUQF1hS39RdERiXHxdcXxWQGRd;Nzg5MjU0QDMyMzAyZTM0MmUzMFJSQjFBaWN1Qm1BTzZ0WndZU2c4OFkvT2I2a2lwNzFwVmVrT1U5dTVDQ2M9;Nzg5MjU1QDMyMzAyZTM0MmUzMGhMWTJxdHl3YjFTMFhPUU1hMndIZFl0TlZvMUtOaTU4S1daZjdGSCtBZTA9;Nzg5MjU2QDMyMzAyZTM0MmUzMEphanZFbVNQd1pIL3g4dmNqOUpSemZLR21CVEIyaHpGUU5tVmU4ZU1jN3c9');

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
