import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import { registerLicense } from '@syncfusion/ej2-base';

registerLicense('Mgo+DSMBaFt/QHRqVVhkXVpFaV1CQmFJfFBmRmlbfVR0ckUmHVdTRHRcQlxjS39adENhX3ZfcXM=;Mgo+DSMBPh8sVXJ0S0J+XE9Ad1RDQmFJYVF2R2BJfFRydl9CZkwxOX1dQl9gSX9TdERqW3lcdn1XQmc=;ORg4AjUWIQA/Gnt2VVhkQlFacl5JXHxLfkx0RWFab116dldMZFpBJAtUQF1hSn5SdkdiUH1YcnJcQmRb;ODU5MjE1QDMyMzAyZTM0MmUzMEhwdkwraDRjcUZjR2xQSHhTaUFkWm9FeTgrSkEyVDNGVGlwd3ZSdnJ3eEk9;ODU5MjE2QDMyMzAyZTM0MmUzMEwrU3dXY1U2akFWek1MS2lDam9ua3h4UTFhUWpKVWozb3RjSnFUZHpuaUk9;NRAiBiAaIQQuGjN/V0Z+WE9EaFtDVmJWfFNpR2NbfE5zfldEalhXVBYiSV9jS31Td0VhWHZcdnZSRmBfVg==;ODU5MjE4QDMyMzAyZTM0MmUzMEphanZFbVNQd1pIL3g4dmNqOUpSemZLR21CVEIyaHpGUU5tVmU4ZU1jN3c9;ODU5MjE5QDMyMzAyZTM0MmUzMFBZeVhxK1d6bjdEangxQ3ovak9TWTdzQzdYYkYwOTRKcnMxODlFejBnbHc9;Mgo+DSMBMAY9C3t2VVhkQlFacl5JXHxLfkx0RWFab116dldMZFpBJAtUQF1hSn5SdkdiUH1YcnNVQGJb;ODU5MjIxQDMyMzAyZTM0MmUzMFJSQjFBaWN1Qm1BTzZ0WndZU2c4OFkvT2I2a2lwNzFwVmVrT1U5dTVDQ2M9;ODU5MjIyQDMyMzAyZTM0MmUzMGhMWTJxdHl3YjFTMFhPUU1hMndIZFl0TlZvMUtOaTU4S1daZjdGSCtBZTA9;ODU5MjIzQDMyMzAyZTM0MmUzMEphanZFbVNQd1pIL3g4dmNqOUpSemZLR21CVEIyaHpGUU5tVmU4ZU1jN3c9');

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
